baabtra/urls.py
from django.urls import path
from . import views

app_name="baabtra"

urlpatterns=[
     path('home',views.baabtra_home),
     path('jscript',views.baabtra_jscript),
     path('new',views.baabtra_new),
     path('new1',views.baabtra_new1),
     path('largest',views.baabtra_largest),
     path('largest3',views.baabtra_largest3),
     path('sum',views.baabtra_sum),
     path('reverse',views.baabtra_reverse),
     path('palindrome',views.baabtra_palindrome),
     path('digits',views.baabtra_digits),
     path('digits1',views.baabtra_digits1),
     path('rtriangle',views.baabtra_rtriangle),
     path('mrtriangle',views.baabtra_mrtriangle),
     path('pyramid',views.baabtra_pyramid),
     path('inversep',views.baabtra_inversep),
     path('new2',views.baabtra_new2),
     path('function',views.baabtra_function),
     path('dom',views.baabtra_dom),
     path('dom1',views.baabtra_dom1),
     path('calculator',views.baabtra_calculator),
     path('password',views.baabtra_password),
     path('jquery',views.baabtra_jquery),
     path('product',views.baabtra_product,name="product"),
     path('addproduct',views.baabtra_addproduct,name="productdetails"),
     path('viewproduct',views.baabtra_viewproduct,name="viewproduct"),
     path('validation',views.baabtra_validation)
     
]

customer/urls.py
from django.urls import path
from . import views
app_name="customer"
urlpatterns=[
    path('home',views.customer_home, name='approve'),
    path('cart',views.customer_cart),
    path('order',views.customer_order, name='orders'),
    path('name',views.customer_name),
    path('home1',views.customer_home1),
    path('box',views.customer_box),
    path('box1',views.customer_box1),
    path('box2',views.customer_box2),
    path('box3',views.customer_box3),
    path('flex',views.customer_flex),
    path('bootstrap',views.customer_bootstrap),
    path('response',views.customer_response)
]

ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('customer/',include('customer.urls')),
    path('baabtra/',include('baabtra.urls')),
    path('facebook/',include('facebook.urls'))
]

facebook/urls.py
from django.urls import path
from . import views
app_name="facebook"
urlpatterns=[

    path('home',views.facebook_home),
    path('home1',views.facebook_home1, name="home"),
    path('management',views.facebook_management, name="manage"),
    path('faculty',views.facebook_faculty, name="fac"),
    path('about',views.facebook_about),
    path('contact',views.facebook_contact, name="cont")


]

baabtra/models.py
from django.db import models

# Create your models here.

facebook/models.py
from django.db import models

# Create your models here.

baabtra/views.py
from django.shortcuts import render

# Create your views here.
def baabtra_home(request):
    return render(request, 'baabtra/home.html')

def baabtra_jscript(request):
    return render(request, 'baabtra/jscript.html')
    
def baabtra_new(request):
    return render(request, 'baabtra/new.html')

def baabtra_new1(request):
    return render(request, 'baabtra/new1.html')

def baabtra_largest(request):
    return render(request, 'baabtra/largest.html')

def baabtra_largest3(request):
    return render(request, 'baabtra/largest3.html')

def baabtra_sum(request):
    return render(request, 'baabtra/sum.html')

def baabtra_reverse(request):
    return render(request, 'baabtra/reverse.html') 

def baabtra_palindrome(request):
    return render(request, 'baabtra/palindrome.html')

def baabtra_digits(request):
    return render(request, 'baabtra/digits.html')

def baabtra_digits1(request):
    return render(request, 'baabtra/digits.html')

def baabtra_rtriangle(request):
    return render(request, 'baabtra/rtriangle.html')   

def baabtra_mrtriangle(request):
    return render(request, 'baabtra/mrtriangle.html') 

def baabtra_pyramid(request):
    return render(request, 'baabtra/pyramid.html')

def baabtra_inversep(request):
    return render(request, 'baabtra/inversep.html')

def baabtra_new2(request):
    return render(request, 'baabtra/new2.html')

def baabtra_function(request):
    return render(request, 'baabtra/function.html')

def baabtra_dom(request):
    return render(request, 'baabtra/dom.html')                                      

def baabtra_dom1(request):
    return render(request, 'baabtra/dom1.html')     

def baabtra_calculator(request):
    return render(request, 'baabtra/calculator.html')

def baabtra_password(request):
    return render(request, 'baabtra/password.html') 

def baabtra_jquery(request):
    return render(request, 'baabtra/jquery.html')

def baabtra_product(request):
    return render(request, 'baabtra/product.html')

def baabtra_addproduct(request):
    return render(request, 'baabtra/addproduct.html')

def baabtra_viewproduct(request):
    return render(request, 'baabtra/viewproduct.html')

def baabtra_validation(request):
    return render(request, 'baabtra/validation.html')            

customer/views.py
from django.shortcuts import render

# Create your views here.
def customer_home(request):
    return render(request,'customer_template/home.html')

def customer_cart(request):
    return render(request,'customer_template/cart.html')

def customer_order(request):
    return render(request,'customer_template/order.html')

def customer_name(request):
    return render(request, 'customer_template/name.html') 

def customer_home1(request):
    return render(request, 'customer_template/home1.html')
    
def customer_box(request):
    return render(request, 'customer_template/box.html')

def customer_box1(request):
    return render(request, 'customer_template/box1.html')

def customer_box2(request):
    return render(request, 'customer_template/box2.html' )

def customer_box3(request):
    return render(request, 'customer_template/box3.html')

def customer_flex(request):
    return render(request, 'customer_template/flex.html')

def customer_bootstrap(request):
    return render(request, 'customer_template/bootstrap.html')

def customer_response(request):
    return render(request, 'customer_template/response.html')

facebook/views.py
from django.shortcuts import render

# Create your views here.

def facebook_home(request):
    return render(request,'facebook_template/home.html')
    

def facebook_home1(request):
    return render(request,'facebook_template/home1.html')

def facebook_management(request):
    return render(request,'facebook_template/management.html')

def facebook_faculty(request):
    return render(request,'facebook_template/faculty.html')

def facebook_about(request):
    return render(request,'facebook_template/about.html') 

def facebook_contact(request):
    return render(request,'facebook_template/contact.html')            

baabtra/templates/baabtra/calculator.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/calculator.css' %}">
</head>
<body>
    <div class= "formstyle">  
        <form name = "form1">  
              
            <!-- This input box shows the button pressed by the user in calculator. -->  
          <input id = "calc" type ="text" name = "answer"> <br> <br>  
          <!-- Display the calculator button on the screen. -->  
          <!-- onclick() function display the number prsses by the user. -->  
          <input type = "button" value = "1" onclick = "form1.answer.value += '1' ">  
          <input type = "button" value = "2" onclick = "form1.answer.value += '2' ">  
          <input type = "button" value = "3" onclick = "form1.answer.value += '3' ">  
           <input type = "button" value = "+" onclick = "form1.answer.value += '+' ">  
          <br> <br>  
            
          <input type = "button" value = "4" onclick = "form1.answer.value += '4' ">  
          <input type = "button" value = "5" onclick = "form1.answer.value += '5' ">  
          <input type = "button" value = "6" onclick = "form1.answer.value += '6' ">  
          <input type = "button" value = "-" onclick = "form1.answer.value += '-' ">  
          <br> <br>  
            
          <input type = "button" value = "7" onclick = "form1.answer.value += '7' ">  
          <input type = "button" value = "8" onclick = "form1.answer.value += '8' ">  
          <input type = "button" value = "9" onclick = "form1.answer.value += '9' ">  
          <input type = "button" value = "*" onclick = "form1.answer.value += '*' ">  
          <br> <br>  
            
            
          <input type = "button" value = "/" onclick = "form1.answer.value += '/' ">  
          <input type = "button" value = "0" onclick = "form1.answer.value += '0' ">  
            <input type = "button" value = "." onclick = "form1.answer.value += '.' ">  
            <!-- When we click on the '=' button, the onclick() shows the sum results on the calculator screen. -->  
          <input type = "button" value = "=" onclick = "form1.answer.value = eval(form1.answer.value) ">  
          <br>   
          <!-- Display the Cancel button and erase all data entered by the user. -->  
          <!-- <input type = "button" value = "Clear All" onclick = "form1.answer.value = ' ' " id= "clear" >  
          <br>    -->
            
        </form>  
        </div>  
        <script>
          function numbers(num)
        </script>
</body>
</html>

baabtra/templates/baabtra/digits.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        var n,r,l=0
        n=prompt("enter the number")
        console.log(n)
        while(n>0)
        {
            r=parseInt(n%10)
            if(l<r)
            {
                l=r
            }
            n=parseInt(n/10)
        }
        console.log("largest digit is",l)
    </script>
</body>
</html>

baabtra/templates/baabtra/digits1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        var n,count=0
        n=prompt("Enter number")
        while(n!=0)
        {
            n=parseInt(n/10)
            count++
        }
        console.log("This is a",count,"digit number")
    </script>
</body>
</html>

baabtra/templates/baabtra/dom1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- <link rel="stylesheet" href=""> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</head>
<body>
    <!-- <div class="parent"> -->
        <div class="mb-3">
            <p><b>TO DO</b></p> 
            <label for="exampleFormControlInput1" class="form-label">Task</label><br>
            <input type="text" id="task">
          </div> <br />
          <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Description</label><br>
            <textarea id="desc"></textarea>
          </div>
          <div>
            <button type="button" onclick="addTask()" >Add</button>
          </div>
          <br />
    <!-- </div> -->
    <table class="table table-bordered" id="todo_tb">
        <thead>
          <tr>
            <th scope="col">S.No</th>
            <th scope="col">Task</th>
            <th scope="col">Description</th>
            <th scope="col">Date</th>
            <th scope="col">Status</th>
            <th scope="col">Action</th>

          </tr>
        </thead>
        <tbody>

        </tbody>
      </table>
      <script>
        var s_no = 0
        var tr_no = 0
        function addTask()
        {
           var tb = document.getElementById("todo_tb")
           var new_tr = document.createElement("tr")//create a new row
           var task = document.getElementById("task")
           var desc = document.getElementById("desc")
           var status = "pending"
           var date = new Date()
           var current_date = date.getDate() + "/" + date.getMonth() + "/" + date.getFullYear()
           console.log(current_date)
           tr_no ++
           var tr_id = "tr" + tr_no
           new_tr.setAttribute("id",tr_id) 
           //creating td inside newly created tr
           var td_sn = new_tr.appendChild(document.createElement("td"))
           var td_task = new_tr.appendChild(document.createElement("td"))
           var td_desc = new_tr.appendChild(document.createElement("td"))
           var td_date = new_tr.appendChild(document.createElement("td"))
           var td_status = new_tr.appendChild(document.createElement("td"))
           var td_action = new_tr.appendChild(document.createElement("td"))
           s_no ++
           td_sn.innerHTML = s_no 
           td_task.innerHTML = task.value
           td_desc.innerHTML = desc.value
           td_date.innerHTML = current_date
           td_status.innerHTML = "<span style='color:red'>pending</span>"
           td_action.innerHTML = "<button onclick=taskCompleted() type='button' class='btn btn-primary'>Completed</button>"

           tb.appendChild(new_tr)//appending newly created tr inside table
           task.value = ""
           desc.value = ""
           

        }
        function taskCompleted()
        {
          var selected_row_id = event.target.parentNode.parentNode.id//to get the tr id
          var selected_row = document.getElementById(selected_row_id)
          var children = selected_row.childNodes
          console.log(children)
          console.log(selected_row_id)
          children[4].innerHTML = "<span style='color:green'>Completed</span>"
          selected_row.style.textDecoration = "line-through"
        }
      </script>

</body>
</html>

baabtra/templates/baabtra/function.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        // function fun()
        // {
        //     console.log(helloooo)
        // }
        // fun()
        function sum(a,b,c)
        {
            // n1=a
            // n2=b
            total=a+b+c

            // console.log(n1+n2)
            return total
        }
        console.log(sum(5,6,7));
       d= sum(5,7,6)
       console.log(d)
        sum(1,2,3)
        // function num(n)
        // {
        //     n=prompt("enter the number")
        //     console.log(n)
        //     if(n%2==0)
        //     {
        //         console.log("even")
        //     }
        //     else
        //     {
        //         console.log("odd")
        //     }
        // }
        // num()
    </script>
</body>
</html>

baabtra/templates/baabtra/inversep.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        var i,j,k,rows=6
        for(i=rows;i>=1;i--)
        {
            for(j=0;j<rows-i;j++)
            {
                document.write("&nbsp;")
            }
            for(k=0;k<i;k++)
            {
                document.write("*")
            }
            document.write("<br />")
        }
    </script>
</body>
</html>

baabtra/templates/baabtra/jscript.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
   
    <script src="{% static 'js/js1.js' %}"></script>

</head>
<body>
    <button onclick="alert('success')">
        sing up
    </button>
    <!-- <script>
      alert('success')
    </script> --> 
    <script>
        var num1=10
        var num2=20
        var sum=num1+num2
        // console.log("result")
        console.log(sum)
        document.write('<br />')
        document.write('<b>',sum,'</b>')
    </script>
</body>
</html>

baabtra/templates/baabtra/largest3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        var a=prompt("enter a")
        console.log(a)
        var b=prompt("enter b")
        console.log(b)
        var c=prompt("enter c")
        console.log(c)
        if(a>=b)
        {
            if(a>=c)
            {
                console.log(a," is largest")
            }
            else
            {
                console.log(c,"is largest")
            }    
        }
        else
        {
            if(b>=c)
            {
                console.log(b,"is largest")
            }
            else
            {
                console.log(c,"is largest")
            }
        }
    
    </script>
</body>
</html>

baabtra/templates/baabtra/mrtriangle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        var i,j
        var rows=6
        for(i=rows;i>=1;i--)
        {
            for(j=1;j<=i;j++)
            {
                document.write("*")
            }
            document.write("<br>")
        }
    </script>
</body>
</html>

baabtra/templates/baabtra/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <!-- <script>
        var a="hai"
        var b="true"
        console.log(typeof(b))
    </script> -->
    <!-- <script>
        var num1=prompt("enter first number")
        console.log(num1)
        var num2=prompt("enter second number")
        console.log(num2)
        var result=parseInt(num1)+parseInt(num2)
        console.log(typeof(num1),typeof(num2))
        console.log(result)
    </script> -->
    <!-- <script>
        var a=confirm("Are you sure you want to delete")
        console.log(a)

    </script> -->
    <!-- <script>
       
        var a,b,c,add,sub,mul,div,mod,inc,dec,exp,bool,
        a=10
        b=20
        c=30
        add=a+b
        sub=b-a
        mul=a*b
        div=a/b
        mod=a%b
        inc=++b
        dec=--a
        exp=c*2
        bool=a<b
        console.log(bool)
        console.log(add)
        console.log(sub)
        console.log(mul)
        console.log(div)
        console.log(mod)
        console.log(inc)
        console.log(dec)
        console.log(exp)
        a+=1
        console.log(a)
        a-=1
        console.log(a)
        a*=2
        console.log(a)
        a/=2
        console.log(a)
        a%=3
        console.log(a)
        a**=2
        console.log(a)
        console.log(a==10)
        console.log(a>b)
        console.log(a<b)
        console.log(a==b)
        console.log(a<=b)
        console.log(a>=b)
        console.log(a!=b)
        console.log(a!==b)
        console.log(a==10)
        console.log(b==20)
        console.log(a>=10&&b>=20)
        console.log(a>10||b<15)
        console.log(!a>10)
 </script> -->
 <!-- <script>
    var num=prompt("enter the number")
    console.log(num)
    if(num%2==0)
    {
        console.log("the number is even")
    }
    else{
        console.log("the number is odd")
    } 
    
  </script> -->
  <!-- <script>
    var day=6
    if(day==0)
    {
        console.log("sunday")
    }
    else if(day==1)
    {
      console.log("monday")  
    }
    else if(day==2)
    {
        console.log("tuesday")
    }
    else if(day==3)
    {
        console.log("wednesday")
    }
    else if(day==4)
    {
        console.log("thursday")
    }
    else if(day==5)
    {
        console.log("friday")
    }
    else if(day==6)
    {
        console.log("saturday")
    }
    else
    {
        console.log("invalid data")
    }
  </script> -->
  <script>
    var day=prompt("enter the number")
    console.log(day)
    switch(day)
    {
        case '0':console.log("Sunday")
               break
        case '1':console.log("Monday")
               break
        case '2':console.log("Tuesday")
               break
        case '3':console.log("Wednesday")
               break
        case '4':console.log("Thursday")
               break
        case '5':console.log("Friday")
               break
        case '6':console.log("Satyrday")
               break
        default:console.log("Invalid day")
        

    }
  </script>
</body>
</html>

baabtra/templates/baabtra/product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
</head>
<body>
    <div class="form1">
        <!-- <button class="b1"><a href="{% url 'baabtra:productdetails' %}">Add product</a></button> -->
    <button class="b1"><a href="/baabtra/addproduct">Add product</a></button>&nbsp;&nbsp;&nbsp;&nbsp;<br><br><br>
    <!-- <button class="b1"><a href="{% url 'baabtra:viewproduct' %}">View product</a></button> -->
    <button class="b1"> <a href="/baabtra/viewproduct">View product</a></button>
</div>
</body>
</html>

customer/templates/customer_template/box.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
</head>
<body>
    <!-- <div class="divt" id="lorem"> 
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Non, ratione?
    </div> -->
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Beatae, nemo.</p>
</body>
</html>

customer/templates/customer_template/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <img src="{% static 'images/H:\E-commerce\ecommerce\customer\static\images\download.jpg' %}">
    <a href="{% url 'customer:orders' %}">view customer</a>
</body>
</html>

facebook/templates/facebook_template/home1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
</head>
<body>
    <section> 
        <div class="d1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;
            <img src="{% static 'images/phone.png' %}" alt="" height="20px">&nbsp; 0484-2911202&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;
            <img src="{% static 'images/email.png' %}" alt="" height="20px">&nbsp; rajagirips@gmail.com&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; TC Details &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <img src="{% static 'images/group.png' %}" alt="" height="20px">&nbsp; Smart Campus&nbsp;&nbsp; 
            <select name="" id="" style="border: 0px;" >
                <option value="">Online Payments</option>
                <option value="">Federal Bank RPS</option>
                <option value="">Federal Bank RKG</option>
                <option value="">Fee Payment Procedures</option>
                <option value="">Robotics/PTA Fee</option>
                <option value="">Bank Challan Copy</option>
            </select>
           
        </div>
    </section>
    <hr>
    <section>
        <div>
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img src="{% static 'images/gr1.png' %}" alt="" height="100px" width="250px"> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
           <img src="{% static 'images/British.png' %}" alt="" height="90px">
        </div>
    </section>
   <div>
    <nav style="background-color: rgb(80, 80, 168); height: 35px; padding-left: 200px;">
        <span style="padding-left: 150px; font-size: 20px; color: white;">HOME</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'facebook:manage' %}"><span style="font-size: 18px; color: white; font-family: Verdana, Geneva, Tahoma, sans-serif;">MANAGEMENT</span></a> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'facebook:fac' %}"><span style="font-size: 18px; color: white; font-family: Verdana, Geneva, Tahoma, sans-serif;">OUR FACULTY</span></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <a href="{% url 'facebook:cont' %}"><span style="font-size: 18px; color: white; font-family: Verdana, Geneva, Tahoma, sans-serif;">CONTACT US</span>
    </nav>
   </div>
    <section>
        <div>
            <img src="{% static 'images/campus.jpg' %}" alt="" height="700px" width="1340px">
        </div>
    </section>
</body>
</html>